apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
        - name: uploader
          image: ghcr.io/
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/config.yaml
              subPath: config.yaml
              name: uploader-config
      volumes:
        - name: uploader-config
          configMap:
            name: uploader-config
