
services:
  minio-server:
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    user: "${UID}:${GID}"

  uploader:
    build: ./uploader
    depends_on:
      - minio-server
    ports:
      - "8080:8080"
    volumes:
      - ./uploader/config.yaml:/app/config.yaml
    command: [ "./app" ]
