env: local

s3storage:
  type: minio
  endpoint: minio:9000
  access_key_id: ROOTUSER
  secret_access_key: CHANGEME123
  ssl: false
  bucket_input: videos
  bucket_text: text

whisper_api: http://host.docker.internal:5678/

kafka:
  brokers:
    - kafka:9092
  read:
    topic: file.uploaded
    group_id: asr
    min_bytes: 1
    max_bytes: 1048576
    commit_interval: 5s
    start_offset: latest

  write:
    topic: asr.done
    client_id: asr-worker
    retries: 5
    max_message_bytes: 1048576
    timeout: 5s
    compression: lz4
