env: local # local, dev, prod

summarizer:
  base_url: http://llm-server:9500/
  model: idk-yet
  prompt: |
    Test
    Test
    Test

storage:
  type: minio
  endpoint: minio:9000
  access_key_id: ROOTUSER
  secret_access_key: CHANGEME123
  ssl: false
  bucket_input: text
  bucket_output: output

kafka:
  brokers:
    - kafka:9092
  read:
    topic: asr.done
    group_id: sum
    min_bytes: 1
    max_bytes: 1048576
    commit_interval: 5s
    start_offset: latest

  write:
    topic: sum.done
    client_id: summarizer-worker
    retries: 5
    max_message_bytes: 1048576
    timeout: 5s
    compression: lz4
