env: local

storage:
  type: minio
  endpoint: minio:9000
  access_key_id: ROOTUSER
  secret_access_key: CHANGEME123
  ssl: false
  bucket: videos

server:
  address: "0.0.0.0:8080"
  timeout: 10s
  idle_timeout: 120s

kafka:
  brokers:
    - kafka:9092
  topic: file.uploaded
  client_id: uploader
  retries: 5
  max_message_bytes: 1048576
  acks: all
  compression: lz4
  timeout: 5s